# Labels for files changed in a PR
frontend:
  - changed-files:
      - any-glob-to-any-file: ["src/**/*", "public/**/*", "index.html"]
background:
  - changed-files:
      - any-glob-to-any-file: "src/background/**/*"
options:
  - changed-files:
      - any-glob-to-any-file: "src/options/**/*"
popup:
  - changed-files:
      - any-glob-to-any-file: "src/popup/**/*"
content-scripts:
  - changed-files:
      - any-glob-to-any-file: "src/content-script/**/*"
automation:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**/*", ".github/dependabot.yml"]
documentation:
  - changed-files:
      - any-glob-to-any-file: ["*.md", "docs/**/*"]
config:
  - changed-files:
      - any-glob-to-any-file: ["package.json", "package-lock.json", "pnpm-lock.yaml", "tsconfig.json", "vite.config.ts", ".eslintrc.cjs", ".prettierrc"]
